version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: url_shortener_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
